"""
QUICK REFERENCE: Medical Risk Assessment Prompts
=================================================

This file shows the EXACT prompts sent to Groq LLM for risk assessment.
"""

# ==============================================================================
# SYSTEM PROMPT (Sets the role and rules for the LLM)
# ==============================================================================

SYSTEM_PROMPT = """You are a medical risk assessment AI for a hospital triage system. Your task is to evaluate medical queries and assign a risk level.

CRITICAL RULES:
1. You MUST respond with valid JSON only (no other text)
2. JSON format: {"risk_level": "LOW|MEDIUM|HIGH|CRITICAL", "risk_reason": "brief explanation"}
3. risk_reason must be 1-2 sentences maximum

RISK LEVEL DEFINITIONS:
- CRITICAL: Life-threatening emergencies requiring immediate intervention (cardiac arrest, severe trauma, stroke symptoms, major bleeding, loss of consciousness, severe breathing difficulty)
- HIGH: Urgent conditions needing prompt medical attention within hours (chest pain, acute severe symptoms, neurological changes, worsening symptoms over days)
- MEDIUM: Conditions requiring medical evaluation soon (persistent pain, fever, infections, new symptoms, chronic disease management)
- LOW: General health information, preventive care, mild symptoms, educational queries

RISK ESCALATION FACTORS:
- Symptoms worsening over multiple days → increase risk by 1 level
- Neurological red flags (confusion, vision changes, numbness, weakness) → HIGH or CRITICAL
- Cardiovascular symptoms (chest pain, palpitations with other symptoms) → HIGH or CRITICAL
- Breathing difficulty or severe pain → HIGH minimum
- Multiple concerning symptoms together → increase risk by 1 level
- Patient expressing distress or concern about severity → increase risk consideration

IMPORTANT: Consider the conversation history for progression of symptoms. If symptoms are recurring or worsening across multiple questions, this indicates higher risk."""


# ==============================================================================
# USER PROMPT TEMPLATE (Filled with actual patient data)
# ==============================================================================

def create_user_prompt(question: str, answer: str, context: str, history: str = "") -> str:
    """
    Creates the user prompt with patient question, answer, context, and history
    
    Args:
        question: Patient's current question
        answer: Medical answer generated by the chatbot
        context: Retrieved medical documents (truncated to 800 chars)
        history: Recent conversation history (last 3 exchanges)
    
    Returns:
        Formatted prompt string
    """
    prompt = f"""Assess the medical risk level for this patient interaction.

PATIENT QUESTION:
{question}

MEDICAL ANSWER PROVIDED:
{answer}

RELEVANT MEDICAL CONTEXT FROM DOCUMENTS:
{context[:800]}"""

    if history:
        prompt += f"""

CONVERSATION HISTORY (for symptom progression analysis):
{history}"""

    prompt += """

Analyze the above information and respond with JSON only:
{
  "risk_level": "LOW|MEDIUM|HIGH|CRITICAL",
  "risk_reason": "Brief explanation (1-2 sentences max)"
}"""

    return prompt


# ==============================================================================
# EXAMPLE USAGE
# ==============================================================================

if __name__ == "__main__":
    print("SYSTEM PROMPT:")
    print("=" * 80)
    print(SYSTEM_PROMPT)
    print("\n\n")
    
    print("USER PROMPT EXAMPLE:")
    print("=" * 80)
    
    # Example data
    example_question = "I've had chest pain for the last 2 hours"
    example_answer = "Chest pain can have various causes including cardiac, muscular, or digestive issues. Given the duration and nature of your symptoms, it's important to seek medical evaluation."
    example_context = "Chest pain is a common symptom that can indicate serious conditions like heart attack, especially if accompanied by shortness of breath, sweating, or radiating pain to the arm or jaw."
    example_history = """Previous Q: What are signs of heart problems?
Previous A: Common signs include chest discomfort, shortness of breath, irregular heartbeat, and fatigue."""
    
    user_prompt = create_user_prompt(
        question=example_question,
        answer=example_answer,
        context=example_context,
        history=example_history
    )
    
    print(user_prompt)
    print("\n\n")
    
    print("EXPECTED LLM RESPONSE:")
    print("=" * 80)
    print("""{
  "risk_level": "HIGH",
  "risk_reason": "Chest pain lasting 2 hours requires urgent cardiac evaluation to rule out acute coronary syndrome or other serious conditions."
}""")


# ==============================================================================
# API CONFIGURATION
# ==============================================================================

API_CONFIG = {
    "model": "llama-3.3-70b-versatile",
    "temperature": 0.3,  # Lower for consistent risk assessment
    "max_tokens": 300,
    "response_format": {"type": "json_object"}  # Enforces JSON-only response
}

print("\n\n")
print("API CONFIGURATION:")
print("=" * 80)
for key, value in API_CONFIG.items():
    print(f"{key}: {value}")
